# Site
title:              Muyang Guo
bio:                'Muyang is a graduate from Georgia Institute of Technology, M.S in CSE and ME, B.S in ME'
description:        "Muyang acquired B.S and M.S degree in Mechanical Engineering from Georgia Tech and is currently pusuring another M.S degree in Computational Science & Engineering"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/avatar.png'
background:         'assets/img/background.jpeg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://muyangguo.xyz

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   muyangguo

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              muyangguo@gmail.com
# twitter:            username
# facebook:           muyang.guo.5
github-url:         MUYANGGUO
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           muyang-guo-445a3465
#xing:              username
# instagram:          muyang_guo
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
# youtube:            muyangguo@gmail.com
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
